name: Generator
on: [push, pull_request]
permissions:
  contents: read
jobs:
  azure-spring-apps:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['16', '>=18']

    name: Test on ${{ matrix.platform }} / Node.js v${{ matrix.node-version }}
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test
